Added improved error handling around downloading and installing packages
stackabletech/agent pull request #326
Opened 2021-10-10 22:55 UTC by soenkeliebau

The agent currently does not delete the target directory for package installations, if the installation fails. This PR adds handling to remove those directories on errors when extracting.

The agent now also specifically requests 'application/gzip' as content type. 
We encountered issues with a webserver which provided our gzipped packages as 'application/tar' and moved the gzip to 'content_encoding' which caused reqwest to transparrently unpack the zip and the subsequent attempt by the agent to unzip this file to fail.

fixes #324 
fixes #325 

## Description

## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)

2021-10-11 07:39 UTC, maltesander submitted a review, later dismissed
LGTM.

2021-10-13 07:52 UTC, nightkr requested changes

2021-10-18 07:11 UTC, nightkr submitted a review, later dismissed

2021-10-18 13:26 UTC, siegfriedweber approved these changes
LGTM (after my changes :grin:)

One downside of this approach is that the Agent tries to recover from a non-recoverable error.

2021-10-19 11:04 UTC, merged